#
# Makefile for the Linux Kernel SOC specific device drivers.
#

obj-$(CONFIG_ARCH_MSM)		+= qcom/
obj-$(CONFIG_ARCH_TEGRA)	+= tegra/
obj-$(CONFIG_SOC_TI)		+= ti/
obj-$(CONFIG_PLAT_VERSATILE)	+= versatile/
CFLAGS_tracer_pkt.o := -I$(src)
